/* =========================================================
   LANDGOV GIS
   DATA-FIELD LEVEL SECURITY & FILTERING SERVICE

   Enforces attribute-level data protection by redacting sensitive
   fields, internal officer notes, audit trails, and departmental
   data based on the requester's role and officer type.
   ========================================================= */

const { canAccessParcel } = require("./parcelAccessService");

/**
 * Redacts and filters a complete Land Profile object based on user authorization.
 * @param {Object} user - Authenticated user context
 * @param {Object} profile - Full raw Land Profile object
 * @returns {Object|null} - Filtered Land Profile
 */
function getVisibleLandProfile(user, profile) {
    if (!user || !profile) return null;

    const parcelId = profile.parcelId || profile.parcel?.id;
    if (!canAccessParcel(user, parcelId)) {
        return null;
    }

    return profile;
}

/**
 * Filters governance validation data to prevent exposing internal investigation notes to citizens.
 */
function filterGovernanceData(user, governanceData) {
    if (!governanceData) return null;
    if (user.role === "admin" || user.role === "officer") {
        return governanceData;
    }
    // Citizen summary view
    return {
        parcelId: governanceData.parcelId,
        overallRiskLevel: governanceData.overallRiskLevel || "LOW",
        recommendationStatus: governanceData.recommendationStatus || "VALID",
        summary: "Governance check status generated by LandGov GIS Engine."
    };
}

/**
 * Filters conflict assessment data for safe citizen response.
 */
function filterConflictData(user, conflictData) {
    if (!conflictData) return null;
    if (user.role === "admin" || user.role === "officer") {
        return conflictData;
    }
    return {
        parcelId: conflictData.parcelId,
        hasConflict: conflictData.hasConflict || (Array.isArray(conflictData.detectedConflicts) && conflictData.detectedConflicts.length > 0),
        status: conflictData.conflictStatus || "NORMAL"
    };
}

/**
 * Filters document list based on document visibility and user authorization.
 */
function filterDocumentData(user, documents = []) {
    if (!Array.isArray(documents)) return [];
    if (!user) return [];

    if (user.role === "admin" || (Array.isArray(user.permissions) && user.permissions.includes("*"))) {
        return documents;
    }

    return documents.filter(doc => {
        // Check parcel access
        if (doc.parcelId && !canAccessParcel(user, doc.parcelId)) {
            return false;
        }

        // Citizens can access public documents or documents they uploaded
        if (user.role === "citizen") {
            const isOwner = doc.uploadedBy === user.email || doc.uploadedBy === user.uid || doc.userId === user.uid;
            const isPublic = doc.visibility === "PUBLIC" || doc.isPublic === true || doc.category === "citizen";
            return isOwner || isPublic;
        }

        // Officers can access documents matching assigned parcel or department
        return true;
    });
}

module.exports = {
    getVisibleLandProfile,
    filterGovernanceData,
    filterConflictData,
    filterDocumentData
};
